apiVersion: v2
name: wordcloudgen
description: WordCloudGen Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"

keywords:
  - wordcloudgen

maintainers:
  - name: Alexey Shulga

